# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  workflow_dispatch:
  push:
    branches: [main, master, practice]

name: render-rmarkdown

jobs:
  render-rmarkdown:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2

      - name: Install rmarkdown
        run: Rscript -e "install.packages('rmarkdown', repos = c(CRAN = 'https://cloud.r-project.org'))"
        
      - name: Install here
        run: Rscript -e "install.packages('here', repos = c(CRAN = 'https://cloud.r-project.org'))"

      - name: Render Rmarkdown files and Commit Results
        run: Rscript -e "rmarkdown::render('analysis/penguins.Rmd', output_dir = here::here('output'))"
